paths:
  # Lista
  /api/cardapio/produtos:
    get:
      summary: Lista todos os produtos
      tags: ["Produtos"]
      responses:
        "200":
          description: Lista de produtos retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  result:
                    type: array
                    items:
                      $ref: "#/components/schemas/Produto"
                  error:
                    type: boolean
  # Lista por ID
  /api/cardapio/produtos/{id_produto}:
    get:
      summary: Lista um produto por ID
      tags: ["Produtos"]
      parameters:
        - name: id_produto
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Produto retornado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  result:
                    type: array
                    items:
                      $ref: "#/components/schemas/Produto"
                  error:
                    type: boolean
  # Cria
  /api/cardapio/produtos/cria:
    post:
      summary: Cria um novo produto
      tags: ["Produtos"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_categoria:
                  type: integer
                nome:
                  type: string
                descricao:
                  type: string
                imagem:
                  type: string
                preco:
                  type: number
                  format: float
                eh_vegano:
                  type: boolean
                eh_sem_gluten:
                  type: boolean
                porcoes:
                  type: integer
      responses:
        "200":
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  result:
                    type: array
                    items:
                      $ref: "#/components/schemas/Produto"
                  error:
                    type: boolean
  # Edita
  /api/cardapio/produtos/edita/{id_produto}:
    put:
      summary: Edita um produto
      tags: ["Produtos"]
      parameters:
        - name: id_produto
          in: path
          required: true
          schema:
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_categoria:
                  type: integer
                nome:
                  type: string
                descricao:
                  type: string
                imagem:
                  type: string
                preco:
                  type: number
                  format: float
                eh_vegano:
                  type: boolean
                eh_sem_gluten:
                  type: boolean
                porcoes:
                  type: integer
      responses:
        "200":
          description: Produto editado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  result:
                    type: array
                    items:
                      $ref: "#/components/schemas/Produto"
                  error:
                    type: boolean

  # Deleta
  /api/cardapio/produtos/deleta/{id_produto}:
    delete:
      summary: Deleta um produto
      tags: ["Produtos"]
      parameters:
        - name: id_produto
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Produto deletado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  result:
                    type: "null"
                  error:
                    type: boolean

components:
  schemas:
    Produto:
      type: object
      properties:
        id_produto:
          type: integer
        id_categoria:
          type: integer
        nome:
          type: string
        descricao:
          type: string
        imagem:
          type: string
        preco:
          type: number
          format: float
        eh_vegano:
          type: boolean
        eh_sem_gluten:
          type: boolean
        porcoes:
          type: integer
