nelmio_api_doc:
    documentation:
        servers:
            - url: https://pratofacil.dynv6.net/api/cardapio
              description: API de Cardápio Digital
            - url: http://localhost:8000/api/cardapio
              description: API de Cardápio Digital (local)
        info:
            title: Cardápio API
            description: API para cardápio digital.
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
