services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cardapio-api-frankenphp
    container_name: cardapio-app
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./:/app
      - ./.docker/Caddyfile.local:/etc/caddy/Caddyfile
    networks:
      - cardapio-network
    depends_on:
      - db
    environment:
      - SERVER_NAME=:80

  db:
    image: mysql:8.0
    container_name: cardapio-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-cardapio_local}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cardapio-network

networks:
  cardapio-network:
    driver: bridge

volumes:
  dbdata:
    driver: local