<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250324134645 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TEMPORARY TABLE __temp__MESA AS SELECT ID, ID_MESA, COMANDA, PEDIDO FROM MESA');
        $this->addSql('DROP TABLE MESA');
        $this->addSql('CREATE TABLE MESA (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ID_MESA INTEGER NOT NULL, COMANDA INTEGER DEFAULT NULL, PEDIDO VARCHAR(255) DEFAULT NULL)');
        $this->addSql('INSERT INTO MESA (ID, ID_MESA, COMANDA, PEDIDO) SELECT ID, ID_MESA, COMANDA, PEDIDO FROM __temp__MESA');
        $this->addSql('DROP TABLE __temp__MESA');
        $this->addSql('CREATE TEMPORARY TABLE __temp__PRODUTO AS SELECT ID_PRODUTO, NOME, DESCRICAO, IMAGEM, PRECO, EH_VEGANO, EH_SEM_GLUTEN, PORCOES, CATEGORIA FROM PRODUTO');
        $this->addSql('DROP TABLE PRODUTO');
        $this->addSql('CREATE TABLE PRODUTO (ID_PRODUTO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, NOME VARCHAR(255) NOT NULL, DESCRICAO VARCHAR(255) NOT NULL, IMAGEM VARCHAR(255) DEFAULT NULL, PRECO DOUBLE PRECISION NOT NULL, EH_VEGANO BOOLEAN NOT NULL, EH_SEM_GLUTEN BOOLEAN NOT NULL, PORCOES INTEGER NOT NULL, CATEGORIA INTEGER NOT NULL)');
        $this->addSql('INSERT INTO PRODUTO (ID_PRODUTO, NOME, DESCRICAO, IMAGEM, PRECO, EH_VEGANO, EH_SEM_GLUTEN, PORCOES, CATEGORIA) SELECT ID_PRODUTO, NOME, DESCRICAO, IMAGEM, PRECO, EH_VEGANO, EH_SEM_GLUTEN, PORCOES, CATEGORIA FROM __temp__PRODUTO');
        $this->addSql('DROP TABLE __temp__PRODUTO');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TEMPORARY TABLE __temp__MESA AS SELECT ID, ID_MESA, COMANDA, PEDIDO FROM MESA');
        $this->addSql('DROP TABLE MESA');
        $this->addSql('CREATE TABLE MESA (ID INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, ID_MESA INTEGER NOT NULL, COMANDA INTEGER DEFAULT NULL, PEDIDO CLOB DEFAULT NULL)');
        $this->addSql('INSERT INTO MESA (ID, ID_MESA, COMANDA, PEDIDO) SELECT ID, ID_MESA, COMANDA, PEDIDO FROM __temp__MESA');
        $this->addSql('DROP TABLE __temp__MESA');
        $this->addSql('CREATE TEMPORARY TABLE __temp__PRODUTO AS SELECT ID_PRODUTO, NOME, DESCRICAO, IMAGEM, PRECO, EH_VEGANO, EH_SEM_GLUTEN, PORCOES, CATEGORIA FROM PRODUTO');
        $this->addSql('DROP TABLE PRODUTO');
        $this->addSql('CREATE TABLE PRODUTO (ID_PRODUTO INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT NULL, NOME CLOB NOT NULL, DESCRICAO CLOB NOT NULL, IMAGEM CLOB DEFAULT NULL, PRECO DOUBLE PRECISION NOT NULL, EH_VEGANO BOOLEAN NOT NULL, EH_SEM_GLUTEN BOOLEAN NOT NULL, PORCOES INTEGER NOT NULL, CATEGORIA INTEGER NOT NULL)');
        $this->addSql('INSERT INTO PRODUTO (ID_PRODUTO, NOME, DESCRICAO, IMAGEM, PRECO, EH_VEGANO, EH_SEM_GLUTEN, PORCOES, CATEGORIA) SELECT ID_PRODUTO, NOME, DESCRICAO, IMAGEM, PRECO, EH_VEGANO, EH_SEM_GLUTEN, PORCOES, CATEGORIA FROM __temp__PRODUTO');
        $this->addSql('DROP TABLE __temp__PRODUTO');
    }
}
