CREATE TABLE PRODUTO (
    ID_PRODUTO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    DESCRICAO TEXT NOT NULL,
    IMAGEM TEXT,
    PRECO REAL NOT NULL,
    EH_VEGANO BOOLEAN NOT NULL,
    EH_SEM_GLUTEM BOOLEAN NOT NULL,
    PORCOES INTEGER NOT NULL,
    CATEGORIA INTEGER NOT NULL    
);