CREATE TABLE RESTAURANTE (
    ID_RESTAURANTE INTEGER PRIMARY KEY CHECK (ID_RESTAURANTE = 1),
    NOME TEXT NOT NULL,
    LOGO TEXT,
    COR_PRIM_1 TEXT,
    COR_PRIM_2 TEXT,
    COR_PRIM_3 TEXT
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    DESCRICAO TEXT NOT NULL,
    IMAGEM TEXT,
    PRECO REAL NOT NULL,
    EH_VEGANO INTEGER NOT NULL,
    EH_SEM_GLUTEN INTEGER NOT NULL,
    PORCOES INTEGER NOT NULL,
    CATEGORIA INTEGER NOT NULL,

    FOREIGN KEY(CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),

    CHECK (EH_VEGANO IN (0,1)),
    CHECK (EH_SEM_GLUTEN IN (0,1))
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INTEGER PRIMARY KEY AUTOINCREMENT,
    DESCRICAO TEXT NOT NULL
);

CREATE TABLE MESA (
    COMANDA INTEGER PRIMARY KEY AUTOINCREMENT,
    NRO_MESA INTEGER NOT NULL,
    STATUS_PAGAMENTO INTEGER NOT NULL DEFAULT 0,

    CHECK (STATUS_PAGAMENTO IN (0,1))
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INTEGER PRIMARY KEY AUTOINCREMENT,
    COMANDA INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    OBSERVACAO TEXT,
    DATA_PEDIDO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STATUS_PEDIDO TEXT NOT NULL DEFAULT 'PREPARANDO',

    FOREIGN KEY(COMANDA) REFERENCES MESA(COMANDA),
    FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),

    CHECK (STATUS_PEDIDO IN ('PREPARANDO', 'PRONTO', 'ENTREGUE'))
);

CREATE VIEW VIEW_PEDIDOS_MESAS AS
    SELECT 
        M.NRO_MESA,
        M.COMANDA,
        P.ID_PEDIDO,
        P.OBSERVACAO,
        P.DATA_PEDIDO,
        P.STATUS_PEDIDO
    FROM PEDIDO P
        LEFT OUTER JOIN MESA M ON M.COMANDA = P.COMANDA
    WHERE P.STATUS_PEDIDO IN ('PREPARANDO', 'PRONTO')
    ORDER BY M.COMANDA
;
