CREATE TABLE PRODUTO (
    ID_PRODUTO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    DESCRICAO TEXT NOT NULL,
    IMAGEM TEXT,
    PRECO REAL NOT NULL,
    EH_VEGANO BOOLEAN NOT NULL,
    EH_SEM_GLUTEN BOOLEAN NOT NULL,
    PORCOES INTEGER NOT NULL,
    CATEGORIA INTEGER NOT NULL    
);

CREATE TABLE MESA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_MESA INTEGER NOT NULL,
    COMANDA INTEGER,
    PEDIDO TEXT,
    DATA_PEDIDO DATETIME DEFAULT (datetime('now', '-3 hours')) NOT NULL
);
