name: deploy

on:
  push:
    branches: [main]

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"

      - name: Install dependencies
        run: composer install

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/config
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: deploy
          deployer-version: "8.0.5"
          private-key: ${{ secrets.PRIVATE_KEY }}
          options: |
            ssh_multiplexing=false
            keep_releases=5
